spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: tatsuki
    password: postgres

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: rakuraku.coffee.rakuraku@gmail.com
    password: zkrvksmccnoaazrn
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

  thymeleaf:
    check-template-location: false
