spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: tatsuki
    password: postgres
  jpa:
   hibernate.ddl-auto: validate #
  thymeleaf.cache: false

  mail:
   host: smtp.gmail.com
   port: 587
   username: berisa0307@gmail.com
   password: urbmcjlscbxnrjfn
